import { openai, supabase } from './config.js';

/* ============================================
LESSON 1: Creating and Storing Embeddings
============================================ */
/*

import podcasts from './content.js';

async function main(input) {
  const data = await Promise.all(
    input.map( async (textChunk) => {
        const embeddingResponse = await openai.embeddings.create({
            model: "text-embedding-ada-002",
            input: textChunk
        });
        return { 
          content: textChunk, 
          embedding: embeddingResponse.data[0].embedding 
        }
    })
  );
  
  // Insert content and embedding into Supabase
  await supabase.from('documents').insert(data); 
  console.log('Embedding and storing complete!');
}

// Make main accessible globally for manual testing
window.main = main;
window.podcasts = podcasts;

// Comment out to prevent auto-run on page load
// main(podcasts)

// Test code - uncomment to verify vector dimensions
const { data } = await supabase
  .from('documents')
  .select('embedding')
  .eq('id', 6)
  .single();

// Parse the vector string to an array
const embeddingArray = JSON.parse(data.embedding);
console.log('Vector dimensions:', embeddingArray.length); // Should be 1536
console.log('String length:', data.embedding.length);     // 19477 characters
*/

/* ============================================
   LESSON 2: Similarity Search with Embeddings
   ============================================ */

// User query about podcasts
const query = "podcasts that are more than 60 minutes";
main(query);

/*
  Create an embedding from the user input and return a 
  semantically matching text chunk from the database 
*/
async function main(input) {
  // Create a vector embedding representing the input text
  const embeddingResponse = await openai.embeddings.create({
    model: "text-embedding-ada-002",
    input,
  }); 
  
  // The vector generated by OpenAI
  const embedding = embeddingResponse.data[0].embedding;
  
  // Query Supabase for nearest vector match
  const { data } = await supabase.rpc('match_documents', {
    query_embedding: embedding,
    match_threshold: 0.50,
    match_count: 1
  });
  console.log(data[0].content, data[0].similarity);
}